#!/bin/bash

# SSL Configuration Script for Nginx (Cloudflare Compatible)
# Run with sudo privileges

set -e

echo "🔒 Configuring Nginx for Cloudflare SSL Compatibility"

# Backup existing configuration
echo "📋 Creating backup of existing configuration..."
sudo cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.backup.$(date +%Y%m%d_%H%M%S)

# Create SSL configuration directory if it doesn't exist
sudo mkdir -p /etc/nginx/conf.d

# Generate DH parameters if they don't exist
if [ ! -f /etc/nginx/dhparam.pem ]; then
    echo "🔑 Generating DH parameters (this may take a few minutes)..."
    sudo openssl dhparam -out /etc/nginx/dhparam.pem 2048
    sudo chmod 600 /etc/nginx/dhparam.pem
fi

# Create modern SSL configuration
echo "⚙️ Creating modern SSL configuration..."
sudo tee /etc/nginx/conf.d/ssl-modern.conf > /dev/null << 'EOF'
# Modern SSL/TLS Configuration for Cloudflare Compatibility
# Generated by RepMotivatedSeller SSL Configuration Script

# SSL Protocols - Enable only TLS 1.2 and 1.3
ssl_protocols TLSv1.2 TLSv1.3;

# Modern Cipher Suites (Cloudflare Compatible)
# Prioritizes ChaCha20-Poly1305 and modern AES-GCM suites
ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384';

# Let the client choose the cipher (TLS 1.3 style)
ssl_prefer_server_ciphers off;

# SSL Session Configuration
ssl_session_cache shared:SSL:10m;
ssl_session_timeout 10m;
ssl_session_tickets off;

# OCSP Stapling
ssl_stapling on;
ssl_stapling_verify on;
resolver 8.8.8.8 8.8.4.4 1.1.1.1 1.0.0.1 valid=300s;
resolver_timeout 5s;

# DH Parameters
ssl_dhparam /etc/nginx/dhparam.pem;

# Security Headers
add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
add_header X-Frame-Options DENY always;
add_header X-Content-Type-Options nosniff always;
add_header X-XSS-Protection "1; mode=block" always;
add_header Referrer-Policy "strict-origin-when-cross-origin" always;
add_header X-Robots-Tag "noindex, nofollow" always;

# Additional Security
ssl_buffer_size 8k;
ssl_early_data on;
EOF

# Test configuration
echo "🧪 Testing Nginx configuration..."
if sudo nginx -t; then
    echo "✅ Configuration test passed"
    
    # Restart Nginx
    echo "🔄 Restarting Nginx..."
    sudo systemctl restart nginx
    
    echo "✅ SSL configuration updated successfully!"
    echo ""
    echo "🔍 Next steps:"
    echo "1. Test your site with SSL Labs: https://www.ssllabs.com/ssltest/"
    echo "2. Verify ChaCha20-Poly1305 support"
    echo "3. Check for A+ rating"
    echo ""
    echo "🌐 Your site should now be fully compatible with Cloudflare!"
    
else
    echo "❌ Configuration test failed"
    echo "🔄 Restoring backup..."
    sudo cp /etc/nginx/nginx.conf.backup.$(date +%Y%m%d)* /etc/nginx/nginx.conf
    echo "Please check your Nginx configuration and try again."
    exit 1
fi
EOF

chmod +x scripts/ssl-config-nginx.sh