#!/bin/bash

# SSL Configuration Script for Apache (Cloudflare Compatible)
# Run with sudo privileges

set -e

echo "🔒 Configuring Apache for Cloudflare SSL Compatibility"

# Detect Apache configuration directory
if [ -d "/etc/apache2" ]; then
    APACHE_DIR="/etc/apache2"
    APACHE_SERVICE="apache2"
elif [ -d "/etc/httpd" ]; then
    APACHE_DIR="/etc/httpd"
    APACHE_SERVICE="httpd"
else
    echo "❌ Apache configuration directory not found"
    exit 1
fi

# Backup existing configuration
echo "📋 Creating backup of existing configuration..."
sudo cp $APACHE_DIR/mods-available/ssl.conf $APACHE_DIR/mods-available/ssl.conf.backup.$(date +%Y%m%d_%H%M%S) 2>/dev/null || true

# Enable required modules
echo "🔧 Enabling required Apache modules..."
sudo a2enmod ssl headers rewrite 2>/dev/null || true

# Create modern SSL configuration
echo "⚙️ Creating modern SSL configuration..."
sudo tee $APACHE_DIR/conf-available/ssl-modern.conf > /dev/null << 'EOF'
# Modern SSL/TLS Configuration for Cloudflare Compatibility
# Generated by RepMotivatedSeller SSL Configuration Script

# SSL Protocols - Enable only TLS 1.2 and 1.3
SSLProtocol -all +TLSv1.2 +TLSv1.3

# Modern Cipher Suites (Cloudflare Compatible)
# Prioritizes ChaCha20-Poly1305 and modern AES-GCM suites
SSLCipherSuite ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384

# Let the client choose the cipher (TLS 1.3 style)
SSLHonorCipherOrder off

# SSL Session Configuration
SSLSessionCache shmcb:/var/cache/mod_ssl/scache(512000)
SSLSessionCacheTimeout 300

# OCSP Stapling
SSLUseStapling on
SSLStaplingCache shmcb:/var/run/ocsp(128000)

# Disable SSL compression (CRIME attack prevention)
SSLCompression off

# Security Headers
Header always set Strict-Transport-Security "max-age=63072000; includeSubDomains; preload"
Header always set X-Frame-Options DENY
Header always set X-Content-Type-Options nosniff
Header always set X-XSS-Protection "1; mode=block"
Header always set Referrer-Policy "strict-origin-when-cross-origin"

# Additional Security
SSLOptions +StrictRequire
SSLInsecureRenegotiation off
EOF

# Enable the configuration
sudo a2enconf ssl-modern 2>/dev/null || true

# Test configuration
echo "🧪 Testing Apache configuration..."
if sudo $APACHE_SERVICE -t; then
    echo "✅ Configuration test passed"
    
    # Restart Apache
    echo "🔄 Restarting Apache..."
    sudo systemctl restart $APACHE_SERVICE
    
    echo "✅ SSL configuration updated successfully!"
    echo ""
    echo "🔍 Next steps:"
    echo "1. Test your site with SSL Labs: https://www.ssllabs.com/ssltest/"
    echo "2. Verify ChaCha20-Poly1305 support"
    echo "3. Check for A+ rating"
    echo ""
    echo "🌐 Your site should now be fully compatible with Cloudflare!"
    
else
    echo "❌ Configuration test failed"
    echo "Please check your Apache configuration and try again."
    exit 1
fi